/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hikvision_yanghui11_frameworkstudy_SMOperator */

#ifndef _Included_com_hikvision_yanghui11_frameworkstudy_SMOperator
#define _Included_com_hikvision_yanghui11_frameworkstudy_SMOperator
#ifdef __cplusplus
extern "C" {
#endif

	/*
	* Class:     com_hikvision_yanghui11_frameworkstudy_SMOperator
	* Method:    write
	* Signature: (I[BIIII)I
	*/
	JNIEXPORT jint JNICALL Java_com_hikvision_yanghui11_frameworkstudy_SMOperator_write
		(JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint, jint);

	/*
	* Class:     com_hikvision_yanghui11_frameworkstudy_SMOperator
	* Method:    read
	* Signature: (I[BIIII)I
	*/
	JNIEXPORT jint JNICALL Java_com_hikvision_yanghui11_frameworkstudy_SMOperator_read
		(JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint,jint);

	/*
	* Class:     com_hikvision_yanghui11_frameworkstudy_SMOperator
	* Method:    mmap
	* Signature: (III)I
	*/
	JNIEXPORT jint JNICALL Java_com_hikvision_yanghui11_frameworkstudy_SMOperator_mmap
		(JNIEnv *, jclass, jint, jint, jint);

	/*
	* Class:     com_hikvision_yanghui11_frameworkstudy_SMOperator
	* Method:    close
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_com_hikvision_yanghui11_frameworkstudy_SMOperator_close
		(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
